- malay/code/d08/d08s07.rpy
Please check 673. I wasn't sure if that is the correct syntax or not.
> d08s07.rpy translated

- spanish/code/d09/d09s01.rpy
I translated all of the content to Spanish and i hope that i did a great work. (: JoshSebas.
> Translating to Spanish

- spanish/code/d08/d08s03.rpy
> Updated d08s03.rpy into Spanish

- spanish/code/d08/d08s02.rpy
> Updated d08s02.rpy into Spanish

- spanish/code/d08/d08s01.rpy
> Updated d08s01.rpy into Spanish

- spanish/code/d08/d08s14.rpy
Hello, VinoVella, I've already translated d08s14.rpy into Spanish
> Updated d08s14.rpy into Spanish

- spanish/code/d09/d09s02.rpy
I have already translated d09s02 into spanish
> updated d09s02 into spanish

- spanish/code/d08/d08s13.rpy
Hello, Vinovella, I've already translated d08s13.rpy into Spanish.
> Updated d08s13.rpy into Spanish

- spanish/code/d09/d09s02.rpy
- spanish/code/d09/d09s03.rpy
- spanish/code/d09/extended/d09s07.rpy
hello vinovella I have already translated d09s07 into spanish
> updated d09s07 into spanish

- spanish/code/d08/d08s12.rpy
Hi, Vinovella, i've already translated d08s12.rpy into Spanish. -JoshSebas
> Updated d08s12.rpy into Spanish

- spanish/code/d08/d08s05.rpy
Hi VinoVella, All of the scene was in Spanish just in one sentence that was in English i translated it into Spanish.
This is the name of the file = d08s05.rpy
> Updated d08s05.rpy into Spanish

- spanish/code/d09/d09s04.rpy
> updated d09s04 into spanish

- spanish/code/d10/d10s04.rpy
Hello, Vinovella, I've already translated d10s04.rpy into Spanish(also the grammar, expressions etc.)
> Updated d10s04.rpy into Spanish

- spanish/code/d09/d09s03.rpy
i have already translated this file
> updated d09s03 into spanish

- spanish/code/d10/d10s03.rpy
Hello, Vinovella, I've already translated d10s03.rpy into Spanish(also the grammar, expressions etc.)
> Updated d10s03.rpy into Spanish

- spanish/code/d10/d10s02.rpy
Hello, Vinovella, I've already translated d10s02.rpy into Spanish(also the grammar, expressions etc.)
> Updated d10s02.rpy into Spanish

- spanish/code/d10/d10s01.rpy
Hello, VinoVella, I've already translated d10s01.rpy into Spanish and the grammar, exclamation stuff....
> Updated d10s01.rpy into Spanish

- spanish/code/d08/d08s08.rpy
> Updated d08s08.rpy into Spanish

- spanish/code/d08/d08s11.rpy
> Updated d08s11.rpy into Spanish

- spanish/code/d08/d08s10.rpy
> Updated d08s10.rpy into Spanish

- spanish/code/d08/d08s07.rpy
> Updated d08s07.rpy into Spanish

- spanish/code/d08/d08s06.rpy
> Updated d08s06.rpy into Spanish

- spanish/code/d08/d08s04.rpy
> Updated d08s04.rpy into Spanish

- spanish/code/d10/d10s05.rpy
Hello, Vinovella, I've already translated d10s05.rpy into Spanish(also the grammar, expressions etc.)
> Updated d10s05.rpy into Spanish

- spanish/code/d09/d09s05.rpy
> updated d09s05 into spanish

- spanish/code/d10p1/d10p1s01.rpy
Hello, Vinovella, I've already translated d10p1s01.rpy into Spanish, also the grammar and expressions in Spanish.
> Updated d10p1s01.rpy into Spanish

- spanish/code/d10p1/extended/d10p1s06b.rpy
Hello, Vinovella, I've already translated d10p1s06b.rpy into Spanish, also i added the expressions, grammar in Spanish.
> Updated d10p1s06b.rpy into Spanish

- spanish/code/d10/d10s07.rpy
Hello, Vinovella, I've already translated d10s07.rpy into Spanish(also the grammar, expressions etc.)
> Updated d10s07.rpy into Spanish

- spanish/code/d10/d10s06.rpy
Hello, Vinovella, I've already translated d10s06.rpy into Spanish(also the grammar, expressions etc.)
> Updated d10s06.rpy into Spanish

- spanish/code/d09/d09s06.rpy
> updated d09s06 into spanish

- spanish/code/d10p1/d10p1s07.rpy
Hello, Vinovella, I've already translated d10p1s07.rpy into Spanish, Also the grammar and the expressions.
> Updated d10p1s07.rpy into Spanish

- spanish/code/d10p1/d10p1s08.rpy
Hello, Vinovella, I've already translated d10p1s08.rpy into Spanish, Also the grammar and the expressions.
> Updated d10p1s08.rpy into Spanish

- spanish/code/d10p2/d10p2s01.rpy
> Update d10p2s01.rpy into spanish

- spanish/code/d10p1/d10p1s03.rpy
Hello, Vinovella, I've already translated d10p1s03.rpy into Spanish, also the grammar and the expressions.
> Updated d10p1s03.rpy into Spanish

- spanish/code/d10p1/d10p1s02.rpy
Hello, Vinovella, I've already translated d10p1s02.rpy into Spanish, Also the grammar and the expressions.
> Updated d10p1s02.rpy into Spanish

- spanish/code/d10p1/d10p1s04.rpy
Hello, Vinovella, I've already translated d10p1s04.rpy into Spanish, Also the grammar and expressions.
> Updated d10p1s04.rpy into Spanish

- spanish/code/d09/d09s08.rpy
I have translated this file into spanish
> updated d09s08 into spanish

- spanish/code/d10p1/d10p1s05.rpy
Hello, Vinovella, I've already translated d10p1s05.rpy into Spanish, Also the grammar and the expressions.
> Updated d10p1s05.rpy into Spanish

- spanish/code/d10p1/d10p1s06.rpy
Hello, Vinovella, I've already translated d10p1s06.rpy into Spanish, Also the grammar and the expressions.
> Updated d10p1s06.rpy into Spanish

- spanish/code/d11/extended/d11s03b.rpy
Hello, Vinovella, I've already translated d11s03b.rpy into Spanish, Also the grammar and the expressions.
> Updated d11s03b.rpy into Spanish

- spanish/code/d11/d11s01.rpy
Hello, Vinovella, I've already translated d11s01.rpy into Spanish, Also the grammar and the expressions.
> Updated d11s01.rpy into Spanish

- spanish/code/d10p2/d10p2s02.rpy
> Update d10p2s02.rpy into spanish

- spanish/code/d10p2/d10p2s03.rpy
> updated d10p2s03 into spanish

- spanish/code/d11/d11s02.rpy
Hello, Vinovella, I've already translated d11s02.rpy into Spanish, Also the grammar and the expressions.
> Updated d11s02.rpy into Spanish

- spanish/code/d11/d11s03.rpy
Hello, Vinovella, I've already translated d11s03.rpy into Spanish.
> Updated d11s03.rpy into Spanish

- spanish/code/d11/d11s04.rpy
Hello, Vinovella, I've already translated d11s04.rpy into Spanish, Also the grammar and the expressions.
> Updated d11s04.rpy into Spanish

- spanish/code/d11/d11s05.rpy
Hello, Vinovella, I've already translated d11s05.rpy into Spanish, Also the grammar and the expressions
> Updated d11s05.rpy into Spansih

- spanish/code/d10p2/d10p2s04-dd.rpy
> Update d10p2s04-dd.rpy into spanish

- spanish/code/d11/d11s06.rpy
Hello, Vinovella, I've already translated d11s06.rpy into Spanish, Also the grammar and the expressions.
> Updated d11s06.rpy into Spanish

- spanish/code/d10p2/d10p2s04-dw.rpy
> updated d10p2s04-dw into spanish

- spanish/code/d11/d11s07.rpy
Hello, VinoVella, I've already translated d11s07.rpy into Spanish, Also the grammar and the expressions.
> Updated d11s07.rpy into Spanish

- spanish/code/d10p2/d10p2s05.rpy
> updated d10p2s05 into spanish

- spanish/code/d12/extended/d12s03.rpy
Hello, Vinovella, I've already translated d12s03.rpy into Spanish, Also the grammar and the expressions.
> Updated d12s03.rpy into Spanish

- spanish/code/d10p2/d10p2s04.rpy
> updated d10p2s04 into spanish

- spanish/code/d12/d12s02.rpy
Hello, Vinovella, I've already translated d12s02.rpy into Spanish, Also the grammar and the expressions.
> Updated d12s02.rpy into Spanish

- spanish/code/d10p2/extended/d10p2s06.rpy
> updated d10p2s06 into spanish

- spanish/code/d12/d12s06.rpy
Hello, Vinovella, I've already translated d12s06.rpy into Spanish. Also the expressions and the grammar.
> Updated d12s06.rpy into Spanish

- spanish/code/d13/extended/d13s02.rpy
Hello, Vinovella, I've already translated d13s02.rpy into Spanish, Also the grammar and the expressions.
> Updated d13s02.rpy into Spanish

- spanish/code/d13/d13s01.rpy
Hello, Vinovella, I've already translated d13s01.rpy into Spanish, Also the grammar and the expressions.
> Updated d13s01.rpy into Spanish

- spanish/code/d13/d13s08.rpy
Hello, Vinovella, I've already translated d13s08.rpy into Spanish, Also the grammar and the expressions.
> Updated d13s08.rpy into Spanish

- spanish/code/d13/d13s09.rpy
Hello, Vinovella, I've already translated d13s09.rpy into Spanish, Also the grammar and the expressions.
> Updated d13s09.rpy into Spanish

- spanish/code/d14/d14s02.rpy
Hello, Vinovella, I've already translated d14s02.rpy into Spanish, Also the grammar and the expressions.
> Updated d14s02.rpy into Spanish

- spanish/code/d14/d14s03.rpy
Hello, Vinovella, I've already translated d14s03.rpy into Spanish, Also the grammar and the expressions.
> Updated d14s03.rpy into Spanish

- spanish/code/screens/screens_fl.rpy
Hello, Vinovella, I've already translated screens_fl.rpy into Spanish, also the grammar and the expressions.
> Updated screens_fl.rpy into Spanish

- spanish/code/d10p2/d10p2s09.rpy
> updated d10p2s09 into spanish

- spanish/code/d14/d14s07.rpy
Hello, Vinovella, I've already translated d14s07.rpy into Spanish, Also the grammar and the expressions.
> Updated d14s07.rpy into Spanish

- spanish/code/d14p2/d14s12.rpy
Hello, Vinovella, I've already translated d14s12.rpy into Spanish, Also the grammar and the expressions.
> Updated d14s12.rpy into Spanish

- spanish/code/d14p2/d14s14.rpy
Hello, Vinovella, I've already translated d14s14.rpy into Spanish, Also the grammar and the expressions.
> Updated d14s14.rpy into Spanish

- spanish/code/d14p2/d14s15.rpy
Hello, Vinovella, I've already translated d14s15.rpy into Spanish, Also the grammar and the expressions.
> Updated d14s15.rpy into Spanish

- spanish/code/d14p2/d14s19.rpy
Hello, Vinovella, I've already translated d14s19.rpy into Spanish, Also the grammar and the expressions.
> Updated d14s19.rpy into Spanish

- spanish/code/d14p2/d14s19_sy.rpy
Hello, Vinovella, I've already translated d14s19_sy.rpy into Spanish, Also the grammar and the expressions.
> Updated d14s19_sy.rpy into Spanish

- spanish/code/data/extended/cg_gallery.rpy
Hello, Vinovella, I've already translated cg_gallery.rpy into Spanish, Also the grammar and the expressions.
> Updated cg_gallery.rpy into Spanish

- spanish/code/d10p2/d10p2_screens.rpy
> updated d10p2-screens

- spanish/code/options.rpy
Hello, Vinovella, I didn't translate any word, i just modified this file justs because it had a lowercase instead of an uppercase....
> Updated options.rpy into Spanish

- spanish/code/common.rpy
Hello, Vinovella, I've already translated common.rpy into Spanish, Also the grammar and the expressions.
> Updated common.rpy into Spanish

- spanish/code/recap.rpy
Hello, Vinovella, I've already translated recap.rpy into Spanish, Also the grammar and the expressions.
> Updated recap.rpy into Spanish

- spanish/code/labels.rpy
Hello, Vinovella, Sorry for missing some of this file translations, I have already translated them.
> Updated labels.rpy into Spanish

- spanish/code/d14/extended/d14s08.rpy
Hello, Vinovella, I've already translated d14s08.rpy into Spanish, Als othe
> Updated d14s08.rpy into Spanish

- spanish/code/hints.rpy
Hello, Vinovella, I've already translated hints.rpy into Spanish, also the grammar and the expressions!
> Updated hints.rpy to Spanish

- malay/code/hints.rpy
I suppose there's a typo on line 574. It should be "Stacy feeds to you" not "Stay feeds to you", I guess?
> hints.rpy translated

- french/code/d12/extended/d12s03.rpy
I've not translate "safe word" and "panic button" cuz it's used in french too so i just let between quotes like that \"safe word\"
> FR TRANSLATION d12s03.rpy
